### ISSUE TITLE
Upgrade to obspy=1.2

### ISSUE THREAD

**Issue by paudetseis** [schaefferaj/StDb#13]
StDb used to work fine with ObsPy version <= 1.1. However, with the new StationXML version, the station start dates and end dates obtained in `query_fdsn_stdb.py` are incorrect:

```
conda create -n stdb python=3.7 obspy -c conda-forge
conda activate stdb
conda list obspy
```
```
# packages in environment at /Users/pascalaudet/anaconda3/envs/stdb:
#
# Name                    Version                   Build  Channel
obspy                     1.2.1            py38h65ad66c_1    conda-forge
```

```
pip install stdb
```
```
query_fdsn_stdb.py -C HH? -S TGTN TGTN
Warning: one of lat,lon,minr,maxr were not set. All values reset to None. 
 
Warning: No Time Range Specified for Search
 
Station/Channel Search Parameters:
   Network:  *
   Stations: TGTN
   Channels: HH?
   Channel Rank: LH,BH,HH
 
Output Files: TGTN.csv and TGTN.pkl
 
Initializing Client (IRIS)...Done

Querying client...Done

Search Complete: 
  1 stations in 1 networks
 
Network: NY
   Station: TGTN
     Lon, Lat, Elev: -128.2727,  61.5267,   0.000
     Start Date: 2013-07-01 00:00:00
Traceback (most recent call last):
  File "/Users/pascalaudet/anaconda3/envs/stdb/bin/query_fdsn_stdb.py", line 512, in <module>
    print ("     End Date:   {0:s}".format(eddt.strftime("%Y-%m-%d %H:%M:%S")))
AttributeError: 'NoneType' object has no attribute 'strftime'
```

However, when installing obspy=1.1 from the beginning, the problem is slightly different:

```
conda create -n stdb python=3.7 obspy=1.1 -c conda-forge
conda activate stdb
conda list obspy
```
```
# packages in environment at /Users/pascalaudet/anaconda3/envs/stdb:
#
# Name                    Version                   Build  Channel
obspy                     1.1.1            py37h917ab60_1    conda-forge
```
```
pip install stdb
```
```
query_fdsn_stdb.py -C HH? -S TGTN TGTN
Warning: one of lat,lon,minr,maxr were not set. All values reset to None. 
 
Warning: No Time Range Specified for Search
 
Station/Channel Search Parameters:
   Network:  *
   Stations: TGTN
   Channels: HH?
   Channel Rank: LH,BH,HH
 
Output Files: TGTN.csv and TGTN.pkl
 
Initializing Client (IRIS)...Done

/Users/pascalaudet/anaconda3/envs/stdb/lib/python3.7/site-packages/obspy/io/stationxml/core.py:84: UserWarning: The StationXML file has version 1.1, ObsPy can deal with version 1.0. Proceed with caution.
  root.attrib["schemaVersion"], SCHEMA_VERSION))
Querying client...Done

Search Complete: 
  1 stations in 1 networks
 
Network: NY
   Station: TGTN
     Lon, Lat, Elev: -128.2727,  61.5267,   0.000
     Start Date: 2013-07-01 00:00:00
Traceback (most recent call last):
  File "/Users/pascalaudet/anaconda3/envs/stdb/bin/query_fdsn_stdb.py", line 512, in <module>
    print ("     End Date:   {0:s}".format(eddt.strftime("%Y-%m-%d %H:%M:%S")))
AttributeError: 'NoneType' object has no attribute 'strftime'
```

It looks like the StationXML version 1.1 is the problem, although I am not sure how to deal with this. We might have to re-write part of StDb to deal with the new obspy and stationxml versions.

**Comment by paudetseis** [comment]
Well, it looks like this is because IRIS is now dumping XML 1.1 and ObsPy has troubles parsing everything. See here: https://github.com/obspy/obspy/issues/2421

I'm not sure how to fix this, but I'll try to look a the code shortly. Otherwise we can't get new StDb files from `query_fdsn_stdb.py`

**Comment by paudetseis** [comment]
Just updated to version 0.1.3 on PyPi, which gets rid of the problem.
